name: Daily Pipeline

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: daily-pipeline
  cancel-in-progress: false

on:

  schedule:
    - cron: "30 5 * * *"

  workflow_dispatch:

jobs:

  pipeline:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Create .env
        run: |
          echo "MANGABAKA_API=${{ secrets.MANGABAKA_API }}" >> .env

      - name: Run Daily Pipeline
        run: npm run daily:incremental

      - name: Commit Updated DB
        run: |

          git config user.name "github-actions"

          git config user.email "actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "daily db update"

          git push